import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'message': 'This is the language?',
          'name': 'English',
          'signin': 'Sign In',
          'createaccount': 'Create an Account',
          'welcome': 'welcome',
          'orderfood': 'Order food from trusted sources',
          'email': 'Email',
          'password': 'Password',
          'emailEnter': 'Enter your Email',
          'passwordEnter': 'Enter your Password',
          'forgertPassword': 'Forget Password',
          'continue': 'Continue',
          'register': 'Register',
          'dontHaveAccount': 'Don\'t have an Account',
          'AlreadyHaveAccount': 'Already have an Account',
          'passwordrecovery': 'Password Recovery',
          'passwordSlogan':
              'Enter your email address or phone number to recover your password',
          'sendLink': 'Send Link',
          'foodProvider': 'Food Providers',
          'seeAll': 'See All',
          'foodieZone': 'FoodieZone',
          'palceOrder': 'Place Order',
          'itemName': 'Item Name',
          'Description': 'Description',
          'Price': 'Price',
          'home': 'Home',
          'Orders': 'Orders',
          'Chat': 'Chat',
          'Profile': 'Profile',
          'SignOut': 'Sign Out',
          'settings': 'Settings',
          'generalSetting': 'General Settings',
          'myAccount': 'My Account',
          'foodDrivier': 'Food Driver',
          'help': 'Help',
          'theme': 'Theme',
          'SwitchMode': "Switch Mode",
          'slogan':
              'Discover the best foods from over 1,000 restaurants and fast delivery to your doorstep'
        },
        'ur_PK': {
          'message': 'زبان؟',
          'name': 'اردو',
          'signin': 'لاگ ان کریں',
          'createaccount': 'رجسٹر کریں',
          'welcome': 'خوش آمدید',
          'register': 'رجسٹر کریں۔',
          'orderfood': 'قابل اعتماد ذرائع سے کھانا آرڈر کریں۔',
          'email': 'ای میل',
          'password': 'پاس ورڈ',
          'passwordEnter': 'اپنا پاس ورڈ درج کریں',
          'emailEnter': 'اپنا ای میل درج کریں۔',
          'forgertPassword': 'پاس ورڈ بھول جانا',
          'dontHaveAccount': 'آپ کے پاس اکاؤنٹ نہیں ہے۔',
          'AlreadyHaveAccount': 'پہلے سے ہی ایک اکاؤنٹ ہے۔',
          'foodProvider': 'خوراک فراہم کرنے والے',
          'seeAll': 'تمام دیکھیں',
          'foodieZone': 'فوڈی زون',
          'passwordRecovery': 'پاس ورڈ کی بازیافت',
          'sendLink': 'لنک بھیجیں',
          'palceOrder': 'حکم صادر کریں',
          'itemName': 'شے کا نام',
          'Description': 'تفصیل',
          'Price': 'قیمت',
          'home': 'گھر',
          'Orders': 'احکامات',
          'Chat': 'گپ شپ',
          'Profile': 'پروفائل',
          'SignOut': 'باہر جائیں',
          'settings': 'ترتیبات',
          'generalSetting': 'عام ترتیبات',
          'myAccount': 'میرا اکاونٹ',
          'foodDrivier': 'فوڈ ڈرائیور',
          'theme': 'خیالیہ',
          'SwitchMode': "سوئچ موڈ",
          'help': 'مدد',
          'passwordSlogan':
              'اپنا پاس ورڈ بازیافت کرنے کے لیے اپنا ای میل پتہ یا فون نمبر درج کریں۔',
          'continue': 'جاری رہے',
          'slogan':
              '1,000 سے زیادہ ریستوراں سے بہترین کھانے کی اشیاء دریافت کریں اور آپ کی دہلیز پر تیز ترسیل'
        },
      };
}
