// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3F4iz0LXoEgFG5RWtgkvB9t27bH5GyAk',
    appId: '1:1078507027664:web:f9c6cebf19e48f18d272d5',
    messagingSenderId: '1078507027664',
    projectId: 'foodiezone-21025',
    authDomain: 'foodiezone-21025.firebaseapp.com',
    storageBucket: 'foodiezone-21025.appspot.com',
    measurementId: 'G-5ZC8005NM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn4ivO2Q_xWigDFgrQm5cskDAY1GvZbsg',
    appId: '1:1078507027664:android:b96463ae01df1117d272d5',
    messagingSenderId: '1078507027664',
    projectId: 'foodiezone-21025',
    storageBucket: 'foodiezone-21025.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU5wawWGOB_HL_32Re3P1rZ7ya6VWp0dM',
    appId: '1:1078507027664:ios:0f640c86980eb721d272d5',
    messagingSenderId: '1078507027664',
    projectId: 'foodiezone-21025',
    storageBucket: 'foodiezone-21025.appspot.com',
    iosBundleId: 'com.example.foodiezone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU5wawWGOB_HL_32Re3P1rZ7ya6VWp0dM',
    appId: '1:1078507027664:ios:b6bbb9a82b0ef8f9d272d5',
    messagingSenderId: '1078507027664',
    projectId: 'foodiezone-21025',
    storageBucket: 'foodiezone-21025.appspot.com',
    iosBundleId: 'com.example.foodiezone.RunnerTests',
  );
}
