// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_pLpbYcPKDTzIdxFUb44ysHktD0WjICg',
    appId: '1:911002275314:web:42e4438ee3a94d72d02f6b',
    messagingSenderId: '911002275314',
    projectId: 'foodiezone-649ee',
    authDomain: 'foodiezone-649ee.firebaseapp.com',
    storageBucket: 'foodiezone-649ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVTtG-6t6Ug9tgpEN37RIPG0Jwac93nq4',
    appId: '1:911002275314:android:24efee50031add31d02f6b',
    messagingSenderId: '911002275314',
    projectId: 'foodiezone-649ee',
    storageBucket: 'foodiezone-649ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGXGJe1KrSAEY9aFZqn50yZu8Gza_JA-w',
    appId: '1:911002275314:ios:451b60ff0d3b0b22d02f6b',
    messagingSenderId: '911002275314',
    projectId: 'foodiezone-649ee',
    storageBucket: 'foodiezone-649ee.appspot.com',
    iosBundleId: 'com.example.foodiezone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGXGJe1KrSAEY9aFZqn50yZu8Gza_JA-w',
    appId: '1:911002275314:ios:ff3bbac179f96239d02f6b',
    messagingSenderId: '911002275314',
    projectId: 'foodiezone-649ee',
    storageBucket: 'foodiezone-649ee.appspot.com',
    iosBundleId: 'com.example.foodiezone.RunnerTests',
  );
}
